### ISSUE TITLE
Sensor abstraction layer unused

### ISSUE THREAD

**Issue by gautamdayal** [ISSUIUC/TARS-Software#66]
We've created an object-oriented design to handle all our sensors (see HighGSensor.cpp or GPSSensor.cpp etc.). These are completely unused right now in the master branch, but actually using them would create a much cleaner interface in flight code and also be very useful for playback/hardware-in-loop functionality that @GigaVoltFlash @cflynn19 @karnapp2 @rbhog  and @NPIPHI have been working on. 

So far, @sendhil2 has these working in branch removed-pointer-struct, and this branch is currently being debugged (things are going wel)

**Comment by redindelible** [comment]
Branch is ready. It works, debugging is done.

**Comment by gautamdayal** [comment]
After stress testing this week, let's open a PR and get it merged so we can use that as our base branch when all the new hardware starts coming in

**Comment by sendhil2** [comment]
I think we can close this too

**Comment by gautamdayal** [comment]
True, closing.
