### ISSUE TITLE
Combining FifoBuffer and HistoryBuffer

### ISSUE THREAD

**Issue by redindelible** [ISSUIUC/TARS-Software#67]
The major difference between FifoBuffer and HistoryBuffer right now is that FifoBuffer has a destructive pop method, which removes items from its buffer, while HistoryBuffer can only be filled and thus may be used to look at recent history. However, using the new FifoView API available in the removed-pointer-struct branch, FifoBuffer will no longer have pop, making it's functionality a superset of HistoryBuffer, obviating the need for the latter. 

We should write the code to calculate derivatives for FifoBuffer, which will let us remove HistoryBuffer and simplify the code base.

**Comment by redindelible** [comment]
It's been implemented in removed-pointer-struct

**Comment by gautamdayal** [comment]
Don't close the issue if it hasn't been thoroughly tested @redindelible

**Comment by sendhil2** [comment]
How about now, now that this change is in removed-pointer-struct?
