### ISSUE TITLE
FSM Revamp

### ISSUE THREAD

**Issue by aidancostello** [ISSUIUC/TARS-Software#69]
The FSM from October launch performed decently well, but there are much-needed improvements. 

1. Change our overall design so that we no longer assume a perfect flight. We shouldn't only be able to transition to the next state of an ideal flight, we should instead be able to transition to any state from any other state (with limitations) for a more accurate representation of what is actually happening.

2. Add an error state. This is important to let us know when something has gone wrong with the rocket. Additionally, when we stage, this will be useful in determining whether or not to light the second stage.

3. Use a wider variety of sensors (acceleration, altitude, orientation, Kalman filter velocity, etc) for state transitions. Use multiple sensors for each state transition as a way to double-check. 

4. Potentially remove buffer usage. During October launch, the acceleration change for drogue and main were distinct enough to just be detected from a single value.

**Comment by gautamdayal** [comment]
The barometric spike when we go supersonic _might_ be a bit of a problem; just something to think about. Wasn't a huge issue this time, but still.

**Comment by gautamdayal** [comment]
Stale, will reopen if required
